In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("fifa21_train.csv")
df1

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,232504,B. Böðvarsson,25,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,214680,G. Gallon,27,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,221489,J. Flores,22,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11699,146717,Anderson Silva,26,Brazil,Barnsley,CM,NaN,Barnsley 2010,"6'2""",179lbs,...,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0,68
11700,236507,T. Conechny,22,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

In [3]:
list(df1.isna().sum())

[0,
 0,
 0,
 0,
 18,
 0,
 288,
 0,
 0,
 0,
 0,
 0,
 41,
 11072,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 41,
 0,
 0,
 41,
 0,
 0,
 0,
 0,
 0,
 0,
 41,
 0,
 41,
 0,
 0,
 41,
 0,
 0,
 0,
 0,
 0,
 7,
 7,
 41,
 0,
 279,
 0,
 0,
 0,
 41,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 59,
 59,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [4]:
def one_for_all(df):
    
    cols = df.columns
    new_cols = []
    rows = df.shape[0]
    
    for col in cols:
        new_col = ""
        for letter in col:
            if letter == " ":
                letter = "_"
                new_col += letter
            else:
                new_col += letter
        new_cols.append(new_col.lower())
    df.columns = new_cols
    
    for col in new_cols:
        na = df[col].isna().sum()
        if na > (25*rows/100):
            df = df.drop([col], axis=1)
        else: df = df[df[col].isna()==False]
    
    num = pd.DataFrame(df.select_dtypes(np.number))
    cat = pd.DataFrame(df.select_dtypes("object"))
    
    return df, num, cat

df1, num, cat = one_for_all(df1)

In [5]:
display(df1)
display(num)
display(cat)

,id,name,age,nationality,club,bp,position,team_&_contract,height,weight,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,196848,I. Ávila,29,Peru,Melgar FBC,ST,ST,Melgar FBC 2019 ~ 2021,"5'7""",154lbs,...,45+2,45+2,46+2,44+2,43+2,43+2,43+2,44+2,19+2,65
11696,232504,B. Böðvarsson,25,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,214680,G. Gallon,27,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,221489,J. Flores,22,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11700,236507,T. Conechny,22,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

,id,age,growth,attacking,crossing,finishing,heading_accuracy,short_passing,volleys,skill,...,gk_reflexes,total_stats,base_stats,pac,sho,pas,dri,def,phy,ova
0,184383,26,1,258,54,47,43,70,44.0,286,...,6,1682,357,69,51,63,63,51,60,64
1,188044,30,0,365,66,79,76,68,76.0,375,...,16,1961,412,83,75,68,82,33,71,77
2,184431,33,0,336,73,76,34,78,75.0,424,...,3,1925,404,80,77,78,86,27,56,80
3,233796,22,13,242,44,42,58,62,36.0,259,...,12,1527,329,57,44,54,57,57,60,59
4,234799,23,8,249,49,37,61,68,34.0,280,...,15,1664,360,66,44,60,64,60,66,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,196848,29,0,290,36,72,65,57,60.0,283,...,14,1638,337,66,68,47,66,33,57,65
11696,232504,25,5,224,62,24,51,59,28.0,248,...,14,1589,347,75,28,56,59,60,69,65
11697,214680,27,4,84,12,14,13,29,16.0,96,...,72,1123,387,72,67,66,72,40,70,70
11698,221489,22,8,286,64,66,51,64,41.0,291,...,16,1603,337,76,60,60,72,26,43,67
11700,236507,22,9,289,43,64,65,64,53.0,267,...,8,1607,336,79,62,56,67,24,48,64

,name,nationality,club,bp,position,team_&_contract,height,weight,foot,joined,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,A. Pasche,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,"Jul 1, 2015",...,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1
1,Alan Carvalho,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,"Jan 16, 2015",...,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2
2,S. Giovinco,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,Right,"Jan 31, 2019",...,56+2,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2
3,J. Evans,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,Right,"Jul 1, 2016",...,58+2,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2
4,Y. Demoncy,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,Right,"Jul 1, 2018",...,64+2,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,I. Ávila,Peru,Melgar FBC,ST,ST,Melgar FBC 2019 ~ 2021,"5'7""",154lbs,Right,"Jul 1, 2019",...,45+2,45+2,45+2,46+2,44+2,43+2,43+2,43+2,44+2,19+2
11696,B. Böðvarsson,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,Left,"Feb 8, 2018",...,60+2,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2
11697,G. Gallon,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,Right,"Jul 1, 2019",...,26+2,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2
11698,J. Flores,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,Right,"Jan 23, 2019",...,44+2,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2
11700,T. Conechny,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,Left,"Jul 22, 2019",...,43+2,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2

In [6]:
# Stars: w/f, sm, ir
# Number: hits
# Inches: height
# Pounds: weight
# Money: value, wage, release_clause
# Time: joined

In [7]:
def starless(df):
    
    values = []
    
    for value in df:
        value = value.replace(' ★', "")
        value = value.replace('★', "")
        value = int(value)
        values.append(value)
    
    df = values

    return df

df1["w/f"] = starless(df1["w/f"])
df1["sm"] = starless(df1["sm"])
df1["ir"] = starless(df1["ir"])

In [8]:
def show_me_the_money(df):
    
    values = []
    
    for value in df:
        value = value.replace('€', "")
        
        if "." in value:
            split = value.split(".")
            value = split[0] + split[1]
            value = value.replace("M", "00000")
            value = value.replace("K", "00")

        else:       
            value = value.replace("M", "000000")
            value = value.replace("K", "000")
            
        value = int(value)
        values.append(value)
    
    df = values

    return df

df1["value"] = show_me_the_money(df1["value"])
df1["wage"] = show_me_the_money(df1["wage"])
df1["release_clause"] = show_me_the_money(df1["release_clause"])
df1["hits"] = show_me_the_money(df1["hits"])

In [9]:
def inches_to_cm(x):
    
    values = []
    
    for value in x:
        value = value.replace('"', "")
        split = value.split("'")
        split[0] = float(split[0])
        split[1] = float(split[1])
        split[0] = split[0]*30.48
        split[1] = split[1]*2.54
        value = split[0]+split[1]
        values.append(value)
    
    return values

df1["height"] = inches_to_cm(df1["height"])
df1["height"]

0        175.26
1        182.88
2        162.56
3        177.80
4        180.34
          ...
11695    170.18
11696    185.42
11697    185.42
11698    167.64
11700    170.18
Name: height, Length: 11211, dtype: float64

In [10]:
df1["joined"] = pd.to_datetime(df1["joined"], errors="coerce")
df1["joined"]

0       2015-07-01
1       2015-01-16
2       2019-01-31
3       2016-07-01
4       2018-07-01
           ...
11695   2019-07-01
11696   2018-02-08
11697   2019-07-01
11698   2019-01-23
11700   2019-07-22
Name: joined, Length: 11211, dtype: datetime64[ns]

In [11]:
df1["weight"] = df1["weight"].map(lambda x: x.rstrip('lbs'))
df1["weight"] = pd.to_numeric(df1["weight"], errors='coerce')

In [12]:
num = df1.select_dtypes(np.number)
num

,id,age,height,weight,growth,value,wage,release_clause,attacking,crossing,...,sm,ir,pac,sho,pas,dri,def,phy,hits,ova
0,184383,26,175.26,161,1,525000,4000,801000,258,54,...,2,1,69,51,63,63,51,60,3,64
1,188044,30,182.88,159,0,8500000,23000,0,365,66,...,4,2,83,75,68,82,33,71,44,77
2,184431,33,162.56,134,0,9000000,49000,15300000,336,73,...,4,2,80,77,78,86,27,56,73,80
3,233796,22,177.80,152,13,275000,4000,694000,242,44,...,2,1,57,44,54,57,57,60,7,59
4,234799,23,180.34,150,8,725000,2000,1400000,249,49,...,3,1,66,44,60,64,60,66,4,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,196848,29,170.18,154,0,550000,500,1200000,290,36,...,3,1,66,68,47,66,33,57,4,65
11696,232504,25,185.42,168,5,625000,3000,891000,224,62,...,2,1,75,28,56,59,60,69,3,65
11697,214680,27,185.42,174,4,1600000,4000,2900000,84,12,...,1,1,72,67,66,72,40,70,3,70
11698,221489,22,167.64,143,8,1100000,2000,1700000,286,64,...,3,1,76,60,60,72,26,43,6,67
11700,236507,22,170.18,143,9,700000,2000,1200000,289,43,...,3,1,79,62,56,67,24,48,8,64

In [13]:
cat = df1.select_dtypes("object")
cat

,name,nationality,club,bp,position,team_&_contract,foot,contract,a/w,d/w,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,A. Pasche,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,Right,2015 ~ 2020,High,Medium,...,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1
1,Alan Carvalho,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan",Right,"Dec 31, 2020 On Loan",High,Low,...,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2
2,S. Giovinco,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,Right,2019 ~ 2022,High,Medium,...,56+2,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2
3,J. Evans,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,Right,2016 ~ 2021,Medium,Medium,...,58+2,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2
4,Y. Demoncy,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,Right,2018 ~ 2021,Low,Medium,...,64+2,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,I. Ávila,Peru,Melgar FBC,ST,ST,Melgar FBC 2019 ~ 2021,Right,2019 ~ 2021,High,Low,...,45+2,45+2,45+2,46+2,44+2,43+2,43+2,43+2,44+2,19+2
11696,B. Böðvarsson,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,Left,2018 ~ 2021,Medium,Medium,...,60+2,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2
11697,G. Gallon,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,Right,2019 ~ 2022,Medium,Medium,...,26+2,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2
11698,J. Flores,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,Right,2019 ~ 2024,High,Medium,...,44+2,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2
11700,T. Conechny,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,Left,2019 ~ 2020,High,Low,...,43+2,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2

In [14]:
positions_stats = df1[['ls', 'st', 'rs',
       'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm',
       'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb',
       'rcb', 'rb', 'gk']].copy()

def test_func(df):
    
    cols = df.columns
    
    for col in cols:
        new_col = []
        for value in df[col]:
            
            if "+" in value:
                split = value.split("+")
                split[0] = int(split[0])
                split[1] = int(split[1])
                value = split[0]+split[1]
            else: value = int(value)
            
            new_col.append(value)
        df[col] = new_col
        
    return df
    
    
positions_stats = test_func(positions_stats)
positions_stats

,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,59,59,59,61,62,62,62,61,64,64,...,60,60,60,60,59,55,55,55,59,16
1,77,77,77,77,77,77,77,77,77,77,...,55,55,55,59,55,50,50,50,55,20
2,75,75,75,80,79,79,79,80,80,80,...,58,58,58,61,55,43,43,43,55,14
3,52,52,52,51,51,51,51,51,55,55,...,60,60,60,58,59,60,60,60,59,16
4,58,58,58,59,59,59,59,59,63,63,...,66,66,66,66,65,63,63,63,65,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,65,65,65,61,63,63,63,61,62,62,...,47,47,47,48,46,45,45,45,46,21
11696,50,50,50,55,52,52,52,55,56,56,...,62,62,62,65,65,63,63,63,65,18
11697,30,30,30,24,26,26,26,24,26,26,...,28,28,28,27,26,28,28,28,26,71
11698,64,64,64,67,65,65,65,67,67,67,...,46,46,46,51,47,37,37,37,47,19
11700,66,66,66,65,65,65,65,65,67,67,...,45,45,45,48,46,38,38,38,46,17

In [15]:
df1 = df1.drop(['ls', 'st', 'rs',
       'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm',
       'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb',
       'rcb', 'rb', 'gk'], axis=1)

df1 = pd.concat([df1, positions_stats], axis=1)
df1

,id,name,age,nationality,club,bp,position,team_&_contract,height,weight,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,175.26,161,...,60,60,60,60,59,55,55,55,59,16
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan",182.88,159,...,55,55,55,59,55,50,50,50,55,20
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,162.56,134,...,58,58,58,61,55,43,43,43,55,14
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,177.80,152,...,60,60,60,58,59,60,60,60,59,16
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,180.34,150,...,66,66,66,66,65,63,63,63,65,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,196848,I. Ávila,29,Peru,Melgar FBC,ST,ST,Melgar FBC 2019 ~ 2021,170.18,154,...,47,47,47,48,46,45,45,45,46,21
11696,232504,B. Böðvarsson,25,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,185.42,168,...,62,62,62,65,65,63,63,63,65,18
11697,214680,G. Gallon,27,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,185.42,174,...,28,28,28,27,26,28,28,28,26,71
11698,221489,J. Flores,22,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,167.64,143,...,46,46,46,51,47,37,37,37,47,19
11700,236507,T. Conechny,22,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,170.18,143,...,45,45,45,48,46,38,38,38,46,17